// // All stories of Endings

monogatari.script({

    'e1':[
        'stop music',
        'play music Cure with loop',
        '最终那个同学在楼顶上哭了出来，他说他很久没有在人前哭出来过了。你和680松了口气。',
        '680pF提议去故宫看看，放松下心情。你也想趁着这个世界没有疫情出去走走。',
        'show background Palace with fadeIn',
        '你们来到了故宫。看到了络绎不绝的游人，他们操着不同地方的口音，整张脸都洋溢着快乐。你们也看到了很多国际友人。大家都不需要戴口罩，不需要间隔两米，不需要出示健康码，不需要出示24小时核酸检测证明。在朱红的城墙边行走时。680pF突然开口:',
        'show character lbl normal with Right',
        'lbl 你是来自DA世界的吧？',
        '你大吃一惊',
        'show character m normal with Left',
        'm 你怎么知道？',
        'lbl 因为我也是。',
        'm 啊？！',
        'lbl 你刚来的时候，社恐，总是担心很多有的没的；总是焦虑自己没搭完的电路，没做完的作业；你没法毫无愧疚感地像我们一样摸鱼，你总是心事重重；你身体出现了异常也不会和我讲，情绪发生了变化也不会告诉我，你害怕麻烦我，害怕被我嫌弃觉得矫情；你们的世界还存在着疫情，你们没办法像年轻人该有的样子一样。',
        'm 你......',
        'lbl 我想说的是，这两个世界都不完美，他们类似于两个极端。要么强调无休止的卷，要么强调无休止的摸鱼。你刚才也说了，这样的世界是不允许正常人活下去的。好的世界，应该是二者皆有的，是既有0又有1的。',
        'lbl 我已经回不去了，只能留在这个世界里。但是你还可以。我希望你回到DA世界之后，能够找到他们的平衡。',
        '你愣住了，的确，你在帮他回忆他的过去的时候，有一种强烈的熟悉的感觉。',
        'hide character m with LfadeOut',
        'hide character lbl with RfadeOut',
        '那朵用代码画出来的彩色向日葵，那个在无数个深夜支撑着你继续生活的电台，那个非常简陋但是胜在创新的游戏demo。',
        '在这个摸鱼至上的世界里，这些东西被认为是不务正业的，难有成就的，在你原来的世界里，这些东西有时依然是这样，总有人比你做的更好甚至好得多，你做的一切似乎就像是一个笑话。',
        '这就是你在DA世界里真实的人生。只是，你从没在DA世界里和任何人讲过这一切，你选择了随波逐流，你克制着自己从来没有走上天台，你试图自己治愈自己。',
        '你的代码和电路板一次一次在夜里崩溃，连同泣不成声或满是失望的自己一起崩溃。',
        '你无数次在想，要是这个世界颠倒过来，不需要学习，不需要科研，大家每天都快快乐乐摸鱼就好了。',
        '今天你在AD世界里见证了这一切，你并没有想象中那样快乐。就像680说的，这两个世界都是不完美的、极端的。对人的异化是显而易见的。',
        '其实你救下来的，是自己。',
        '是从未在DA世界里表现出来的、被压制的另一面的你。',
        '希望你回到DA世界后，没记住680pF也无所谓，要记住今天的感觉。记住尝试的感觉，记住帮助与被帮助的感觉，记住你对躺和卷怎样中和的思考。',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Cure with fade 3',
        'jump Start'
    ],

    'e2':[
        'stop music',
        'play music Cure with loop',
        '消防员及时赶到，一边到楼顶营救一边在楼下准备好防护措施。最终他被救了下来，送上了救护车。',
        'show background Library with fadeIn',
        '你和680pF决定在校园里走一走，驱赶一下沉重的气氛，走在学堂路的树下，680pF突然开口:',
        'show character lbl normal with Right',
        'show character m normal with Left',
        'lbl 你是来自DA世界的吧？',
        '你大吃一惊',
        'm 你怎么知道？',
        'lbl 因为我也是。',
        'm 啊？！',
        'lbl 你刚来的时候，社恐，总是担心很多有的没的；总是焦虑自己没搭完的电路，没做完的作业；你没法毫无愧疚感地像我们一样摸鱼，你总是心事重重；你身体出现了异常也不会和我讲，情绪发生了变化也不会告诉我，你害怕麻烦我，害怕被我嫌弃觉得矫情；你们的世界还存在着疫情，你们没办法像年轻人该有的样子一样。',
        'm 你......',
        'lbl 我以为你能救下那个孩子。',
        'm （咬了咬嘴唇）我尽力了，我想不出其他的办法了。',
        '680pF拍了拍你的肩膀。',
        '没有人会怪你，你已经做的很好了，为消防员的救援争取了很多时间，也听他说了很多话。你救了他。',
        'm 但是我能感觉到，被救下来的，只有他的身体。',
        'show background Hospital with fadeIn',
        '不知不觉已经走到了校医院门口，你和680在小桥边停下，看着潺潺的流水。',
        '医院里的人络绎不绝，摆烂心理科正人满为患。680pF抬头看着天空。',
        'lbl 希望他会在这个世界里遇到更多的救赎。',
        'hide character m with LfadeOut',
        'hide character lbl with RfadeOut',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Cure with fade 3',
        'jump Start'
    ],

    'e3':[
        'stop music',
        'play music Evening with loop',
        '他已然说了最后的告别，你错过了拉住他的机会。',
        '你低头，拳头攥紧，指甲扎进手心。',
        '680pF拍了拍你颤抖的背，没有说话，拉着你的胳膊，带你离开了人群。你像丢了魂魄一样，毫无知觉地被他拉着走。',
        'show background Purple with fadeIn',
        '一路踉跄，你被680pF拉到操场一角。沉默地看着680pF，你深吸了一口气。',
        'show character m normal with Left',
        'show character lbl normal with Right',
        'm 他终于在讲他的心里话，可惜是第一次也是最后一次了。',
        'lbl 你在后悔没有出手劝阻他吗？',
        'm 可能即便我向他喊话了，我也不知道应该和他说些什么。但是那是最后的机会，我没有把握住，或许如果我说了什么，他不会跳楼，或者可以等到救援人员到来。',
        'lbl 你觉得会有用吗？他在学校的这几年都没有得到应有的关心，你这算什么？临终关怀吗？',
        '你沉默了，680pF说的不无道理。你始终有点后悔，理应抓住机会尝试帮助一下他的，起码不会让他那么没有留恋地就离开这个世界。',
        '680pF说，过去的事情没有回头的余地，不如用未来去弥补遗憾。',
        'hide character m with LfadeOut',
        'hide character lbl with RfadeOut',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Evening with fade 3',
        'jump Start'
    ],

    'e4':[
        'stop music',
        'play music Evening with loop',
        '你听见呼啸的风声，你知道一切结束了。',
        '人群迅速四散开来，你不忍心再看，匆匆逃离了现场。',
        '680pF告诉你没事的，不是你的错。',
        '可是你想的是，如果当时见面的时候，明知他可能出了问题，要是能多和他聊聊，多了解一下他，或许今天不会是这样的结局。',
        '可惜没有如果。',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Evening with fade 3',
        'jump Start'
    ],

    'e5':[
        'stop music',
        'play music Evening with loop',
        'show background Palace with fadeIn',
        '你和680去了故宫，决定散散心。',
        '你们来到了故宫。看到了络绎不绝的游人，他们操着不同地方的口音，整张脸都洋溢着快乐。你们也看到了很多国际友人。大家都不需要戴口罩，不需要间隔两米，不需要出示健康码，不需要出示24小时核酸检测证明。',
        '你的心情始终有些沉重，你总能想起那个站在楼顶的他。',
        '中间680低头看了一阵手机，然后面色凝重地告诉你，他从楼上跳了下来。什么都没来得及做，人就已经去世了。',
        '人们在附近找到了他的电脑，看到了里面的代码，据说他跳下来之前嘱咐下面的同学把这段代码发给他的家人。',
        '代码运行起来，是他二十余年的经历和遗憾，快乐和希望，还有生命最后的痛苦。',
        '在他离开之后，大家用这种方式才得以了解他。',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Evening with fade 3',
        'jump Start'
    ],

    'e6':[
        'stop music',
        'play music Cure with loop',
        '楼下的同学们七嘴八舌地鼓励了他一会儿，他站在楼顶，放声哭了起来，颤抖地像随时都会飘落下来。',
        '消防车到了，救援人员冲到天台，强行打开天台的门，将他拉了下来。',
        '救护车把他拉走的时候，你看到他强撑着坐起来，脸上还挂满了泪痕，用口型对你说了一句话。',
        'cd “谢谢"',
        'show background Library with fadeIn',
        '你和680并肩走在校园里，虽然他被救下来了，但是你们仍然心有余悸。',
        'show character m normal with Left',
        'show character lbl normal with Right',
        'm 你说当时楼下那些同学说的都是真心话吗？',
        'lbl 我不知道，或许是，或许不是。',
        'm 但是，不管是不是真心话，他们都应该有所触动，有所改变吧。',
        'lbl 你觉得他算是真的好起来了吗？',
        'm 我觉得不是，真正需要接纳他的人，是他自己。',
        'lbl 他还需要一段时间。',
        'lbl 走吧。',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'hide character m with LfadeOut',
        'hide character lbl with RfadeOut',
        'centered End',
        'stop music Cure with fade 3',
        'jump Start'
    ],

    'e7':[
        'stop music',
        'play music Evening with loop',
        'show background Library with fadeIn',
        '你和680又在校园里四处逛了逛，看到了很多有趣的、和你原本世界完全不同的景象。',
        '中间680低头看了一阵手机，然后面色凝重地告诉你，他从楼上跳了下来。什么都没来得及做，人就已经去世了。',
        '人们在附近找到了他的电脑，看到了里面的代码，据说他跳下来之前嘱咐下面的同学把这段代码发给他的家人。',
        '代码运行起来，是他二十余年的经历和遗憾，快乐和希望，还有生命最后的痛苦。',
        '在他离开之后，大家用这种方式才得以了解他。',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Evening with fade 3',
        'jump Start'
    ],

    'e8':[
        'stop music',
        'play music Evening with loop',
        'show background Library with fadeIn',
        '你又在校园里四处逛了逛，看到了很多有趣的、和你原本世界完全不同的景象。',
        '你渐渐觉得无聊了。',
        '突然你眼前一片眩晕。睁眼时你回到了DA世界，你发现你正在玩一个雷系今年新出的游戏《Special date Of Ordinary》。',
        'centered End',
        'stop music Evening with fade 3',
        'jump Start'
    ]
});